### ISSUE TITLE
Error in response handling

### ISSUE THREAD

**Issue by rish07** [DarthBenro008/gunfollower#2]
Hey @DarthBenro008,

There seems to be an exception the response handling for this particular user. Can you check?

<img width="697" alt="image" src="https://user-images.githubusercontent.com/49035175/145087471-218213b8-a28f-4d92-85ab-f35d01c09c74.png">

**Comment by DarthBenro008** [comment]
Hey @rish07 ,

Thanks for bringing this issue up! It has been successfully fixed in 7ef90e720cc2ad297fd096e8c6841f6de5d42500 and has been included in the [`v0.1.3` release](https://github.com/DarthBenro008/gunfollower/releases/tag/v0.1.3)

I can see that you are using macOS, kindly upgrade gunfollower using `brew upgrade gunfollower`

If you are facing any issue in updating, please run the following commands:

```bash
brew uninstall gunfollower
brew untap DarthBenro008/gunfollower
brew tap DarthBenro008/gunfollower
brew install gunfollower
```

![image](https://user-images.githubusercontent.com/31009634/145091402-eb2a8ef6-986b-4b09-a5ab-2e62e997311e.png)


Feel free to reopen this issue, if it persists 😃
